import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/SessionProvider'
import Navbar from '@/component/Navbar/Navbar'
import Footer from '@/component/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>        
       <Provider>
        <Navbar />
       {children}
       </Provider>
        <Footer />
        </body>
    </html>
  )
}
